version: '2.2'
services:
  postgres:
    image: "postgres:11.5-alpine"
    ports: 
        - "5432:5432"
    environment:
        - POSTGRES_USER=testdb
        - POSTGRES_PASSWORD=test123
        - POSTGRES_DB=testdb
    volumes:
      - postgres:/var/lib/postgresql/data/
volumes:
  postgres: