/*
 * Test api for project
 *
 * This api is a test version to connect the backend and frontend
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// GenericTestAnswers - The answers to a generic test
type GenericTestAnswers struct {

	// the id of the account that performed this test
	AccountID string `json:"accountID,omitempty"`

	// the array of answers for this questionnaire
	Answers []AnswerToQuestion `json:"answers,omitempty"`
}
