/*
 * Test api for project
 *
 * This api is a test version to connect the backend and frontend
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// GetAccountIdResponse - response to provide account details
type GetAccountIdResponse struct {

	// The id of the account
	ID string `json:"ID"`

	// the name of the account
	Name string `json:"Name"`

	// the email address of the account
	Email string `json:"Email"`
}
