/*
 * Test api for project
 *
 * This api is a test version to connect the backend and frontend
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// LogoutAccount - schema to revoke access with the specific account
type LogoutAccount struct {

	// access token that needs to be revoked to log out
	AccessToken string `json:"accessToken"`
}
