/*
 * Test api for project
 *
 * This api is a test version to connect the backend and frontend
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// JwtAccountDetails - the account details provided when the user logs in as a JWT token
type JwtAccountDetails struct {

	// The new access token
	AccessToken string `json:"accessToken"`
}
