/*
 * Test api for project
 *
 * This api is a test version to connect the backend and frontend
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Test - test to perform
type Test struct {

	// id of the test
	TestID string `json:"testID,omitempty"`

	// name of the test
	TestName string `json:"testName,omitempty"`
}
