/*
 * Test api for project
 *
 * This api is a test version to connect the backend and frontend
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Project - a project object
type Project struct {

	// the id of a project
	ProjectID string `json:"projectID,omitempty"`

	// the name of a project
	ProjectName string `json:"projectName,omitempty"`
}
