/*
 * Test api for project
 *
 * This api is a test version to connect the backend and frontend
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AccountDetails - the account details provided when the user logs in as a JWT token
type AccountDetails struct {

	// The account id.
	AccountID string `json:"accountID"`

	// logged in SessionID
	SessionID string `json:"sessionID"`

	// The access token.
	AccessToken string `json:"accessToken"`

	// The refresh token.
	RefreshToken string `json:"refreshToken"`

	// type of account
	AccountType string `json:"accountType"`
}
