/*
 * Test api for project
 *
 * This api is a test version to connect the backend and frontend
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// SignUp - schema for signing up
type SignUp struct {

	// account id of the account that invites the new user
	SenderAccountID string `json:"senderAccountID"`

	// the email address of the newly invited person
	EmailAddress string `json:"emailAddress"`
}
