/*
 * Test api for project
 *
 * This api is a test version to connect the backend and frontend
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// GenericTest - schema of a generic test
type GenericTest struct {

	// Title of questionnaire
	Title string `json:"title"`

	// Description of questionnaire
	Description string `json:"description"`

	// To determine whether the answers should be displayed at the end of the questionnaire
	DisplayAnswers bool `json:"displayAnswers"`

	// Final remakrs at the end of the questionnaire
	FinalRemark string `json:"finalRemark"`

	Questions []GenericTestQuestions `json:"questions"`
}
