/*
 * Test api for project
 *
 * This api is a test version to connect the backend and frontend
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AccountCreation - the schema to create the new account
type AccountCreation struct {

	// first name of the new user
	FirstName string `json:"firstName"`

	// last name of the new user
	LastName string `json:"lastName"`

	// the id of the account that invited the new user
	SenderAccountID string `json:"senderAccountID"`

	EmailAddress string `json:"emailAddress"`
}
