/*
 * Test api for project
 *
 * This api is a test version to connect the backend and frontend
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// TestsProject - tests that the account needs to perform for this specific project
type TestsProject struct {

	// array of tests
	TestsToPerform []Test `json:"testsToPerform,omitempty"`
}
