/*
 * Test api for project
 *
 * This api is a test version to connect the backend and frontend
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// JwtAccountDetails1 - the account details provided when the user logs in as a JWT token
type JwtAccountDetails1 struct {

	// The jwt token with all information.
	JWT string `json:"JWT"`
}
