/*
 * Test api for project
 *
 * This api is a test version to connect the backend and frontend
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GenericTestQuestions struct {

	Question string `json:"question,omitempty"`

	QuestionType string `json:"questionType,omitempty"`

	Answers []string `json:"answers,omitempty"`
}
