/*
 * Test api for project
 *
 * This api is a test version to connect the backend and frontend
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AnswerToQuestion - the answer to a question
type AnswerToQuestion struct {

	// the question number
	Question int32 `json:"question,omitempty"`

	// an answer to a question
	Answer string `json:"answer,omitempty"`

	// the time in milliseconds to answer the question
	TimeToAnswer float32 `json:"timeToAnswer,omitempty"`
}
